### ISSUE TITLE
Syntax Error upon initial run against HTML file

### ISSUE THREAD

**Issue by jdeplato** [exp0se/bro-intel-generator#2]
When executing this against an HTML file (saved as a full web-page through FireFox) I am receiving the following error:

./intel_generator.sh: line 4: syntax error near unexpected token `newline'

./intel_generator.sh: line 4: `<!DOCTYPE html>'

I am executing the command:
./intel_generator.sh -f Test1.html -t

**Comment by exp0se** [comment]
Hm, not sure what is going on. Can you say which OS are you using and attach this html file? Also could you try to just download this html page via wget?
Can you try this one:
https://www.fireeye.com/blog/threat-research/2014/11/operation-poisoned-handover-unveiling-ties-between-apt-activity-in-hong-kongs-pro-democracy-movement.html

**Comment by jdeplato** [comment]
Using latest version of Kali Linux.

wget gave me the same error

URL I am using is: https://nakedsecurity.sophos.com/2015/03/06/from-the-labs-new-developments-in-microsoft-office-malware/

wget the URL you provided gives me the same error as well

**Comment by exp0se** [comment]
Well, URL you posted doesn't contain any suitable indicators - so there will be no results. But of course script shouldn't crash like that. Did you save it directly or downloaded it via git?
It appears to me that your copy was altered or corrupted somehow - can you just delete your copy and download it via git clone?
I just tested it in Kali with fresh copy from git and i didn't have any problems.

**Comment by jdeplato** [comment]
deleting and re-cloning solved the problem. Thanks!
